language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
gemfile:
  - test_rails_app/gemfiles/rails_4.2.gemfile
  - test_rails_app/gemfiles/rails_5.1.gemfile
  - test_rails_app/gemfiles/rails_5.2.gemfile
env:
  global:
    TRAVIS: true
sudo: false
cache: bundler
CODECLIMATE_REPO_TOKEN: 11158e372b49d660cd14d15f351b0326e7bcdd29e7e31f271a2055530212f3e3
